Repository s-m-quadri/geca-labs, pull requests merged in 2025-08, with the labels that each got.

#2 Submission of Lab 0 By BT23F05F059
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Incomplete

#5 Submission of Lab 0 by BT23F05F047
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Incomplete

#7 Submission of Lab 0 by BT23F05F042
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#8 Submission of Lab 0 by BT23F05F045
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: duplicate, Lab 0, Accepted

#10 Submission of Lab 0 by BT23F05F052
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#14 Submission of Lab 0 by BT23F05F051
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#21 Submission of Lab 0 by BT23F05F019
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#22 Submission of Lab 0 by BT23F05F013
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#23 Submission of lab 0 by BT23F05F002
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#40 Submission of Lab 0 by BT24S05F006
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#41 Submission of lab 0 by BT23F05F061
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#57 Submission of Lab 0 by BT23F05F003
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#54 Submission of Lab 0 by BT23F05F025
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#6 Submission of Lab 0 by BT23F05F049
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#26 Submission of Lab 0 by BT23F05F018
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 0, Accepted

#95 Submission of Lab 01 by BT24F05F001
  countdown.py
  print_letters.py
  sum_numbers.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#18 Submission of Lab 01 by BT23F05F048
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Incomplete, Lab 01

#19 Submission of Lab 01 by BT23F05F052
  fact.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Incomplete, Lab 01

#38 Submission of Lab 00 by BT24S05F005
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, Incomplete

#71 Submission of Lab 00 by BT23F05F004
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00

#87 Submission of Lab 01 by BT24S05F005
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01, outdated-branch

#58 Submission of Lab 00 by BT23F05F006
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, Incomplete

#59 Submission of Lab 00 by BT23F05F039
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, ⚠️ Incomplete

#27 Submission of Lab 00 by BT23F05F007
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, ⚠️ Incomplete

#43 Submission of Lab 00 by BT24S05F001
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, ⚠️ Incomplete

#70 Submission of Lab 00 by BT23F05F035
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, 😵 Conflict! Please Give Access to Resolve

#52 Submission of Lab 00 by BT23F05F030
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  output.txt
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+.py
  z.py
Labels: Lab 00, 😵 Conflict! Please Give Access to Resolve

#122 Submission of Lab 02 by BT23F05F044
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#124 Submission of Lab 00 by BT23F05F032
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00

#126 Submission of Lab 00 by BT24S05F009
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00

#132 Submission of Lab 01 by BT23F05F026
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: ⚠️ Incomplete, Lab 01

#102 Submission of Lab 02 by BT23F05F003
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: ⚠️ Incomplete, Lab 02

#75 Submission of Lab 01 by BT23F05F003
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: ⚠️ Incomplete, Lab 01

#63 Submission of Lab 01 by BT23F05F049
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: ⚠️ Incomplete, Lab 01

#140 Submission of Lab 02 by BT23F05F052
  merge_sort_basic.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: 🎉 Accepted, Lab 02

#141 Submission of Lab 02 by BT23F05F048
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#143 Submission of Lab 00 by BT23F05F057
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00

#155 Submission of Lab 03 by BT23F05F052
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#159 Submission of Lab 01 by BT24S05F009
  countdown.py
  print_letters.py
  sum_numbers.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#145 Submission of Lab 01 by BT24S05F007
  countdown.py
  print_letters.py
  sum_numbers.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#154 Submission of Lab 03 by BT23F05F047
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: ⚠️ Incomplete, Lab 03

#68 Submission of Lab 01 by BT23F05F047
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: ⚠️ Incomplete, Lab 01

#207 Submission of Lab 01 by BT23F05F023
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#76 Submission of Lab 01 by BT23F05F006
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: ⚠️ Incomplete, Lab 01

#86 Submission of Lab 01 by BT23F05F061
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#120 Submission of Lab 02 by BT23F05F006
  merge_sort_basic.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: 🎉 Accepted, Lab 02

#129 Submission of Lab 01 by BT23F05F030
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#130 Submission of Lab 01 by BT23F05F035
  countdown.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#164 Submission of Lab 01 by BT23F05F002
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#165 Submission of Lab 02 by BT23F05F002
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#167 Submission of Lab 00 by BT23F05F065
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, 🎉 Accepted

#168 Submission of Lab 01 by BT23F05F0065
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#169 Submission of Lab 02 by BT23F05F065
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: 🎉 Accepted, Lab 02

#172 Submission of Lab 03 by BT23F05F003
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: 🎉 Accepted, Lab 03

#175 Submission of Lab 01 by BT23F05F016
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#181 Submission of Lab 02 by BT23F05F016
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: 🎉 Accepted, Lab 02

#183 Submission of Lab 03 by BT23F05F002
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: 🎉 Accepted, Lab 03

#184 Submission of Lab 03 by BT23F05F016
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: 🎉 Accepted, Lab 03

#185 Submission of Lab 01 by BT24S05F006
  countdown.py
  print_letters.py
  sum_numbers.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#190 Submission of Lab 02 by BT24S05F001
  merge_sort_basic.py
  merge_sort_descending.py
  merge_sort_strings.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: 🎉 Accepted, Lab 02

#193 Submission of Lab 01 by BT23F05F067
  countdown.py
  print_letters.py
  sum_numbers.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#205 Submission of Lab 02 by BT23F05F025
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: 🎉 Accepted, Lab 02
