Repository s-m-quadri/geca-labs, pull requests merged in 2025-10, with the labels that each got.

#281 Submission of Lab 05 by BT23F05F033
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: 🎉 Accepted, Lab 05

#201 Submission of Lab 02 by BT23F05F028
  merge_sort_basic.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: ⚠️ Incomplete, Lab 02

#240 Submission of Lab 03 by BT23F05F021
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: ⚠️ Incomplete, Lab 03

#198 Submission of Lab 02 by BT23F05F021
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: ⚠️ Incomplete, Lab 02
