Repository s-m-quadri/geca-labs, pull requests merged in 2025-09, with the labels that each got.

#212 Submission of Lab 01 by BT23F05F057
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#214 Submission of Lab 02 by BT23F05F057
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#176 Submission of Lab 02 by BT23F05F004
  merge_sort_basic.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: ⚠️ Incomplete, Lab 02

#178 Submission of Lab 03 by BT23F05F004
  binary_search_demo_steps.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: ⚠️ Incomplete, Lab 03

#162 Submission of Lab 02 by BT23F05F049
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: ⚠️ Incomplete, Lab 02

#220 Submission of Lab 03 by BT24S05F009
  binary_search.py
  binary_search_demo_steps.py
  binary_search_demo_visual.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
Labels: Lab 03

#186 Submission of Lab 02 by BT24S05F002
  merge_sort_basic.py
  task_count_inversions.py
  task_merge_sorted_lists.py
Labels: ⚠️ Incomplete, Lab 02

#166 Submission of Lab 01 by BT23F05F028
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: 🎉 Accepted, Lab 01

#56 Submission of Lab 00 by BT23F05F024
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00, ⚠️ Incomplete

#224 Submission of Lab 03 by BT24S05F002
  binary_search.py
  binary_search_demo_steps.py
  binary_search_demo_visual.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#225 Submission of Lab 04 by BT24S05F005
  greedy knapsack.py
  task_4.1.py
  task_4.2.py
  task_4.3.py
  task_4.4.py
  task_4.5.py
  task_4.6.py
Labels: Lab 04

#227 Submission of Lab 03 by BT23F05F067
  binary_search.py
  binary_search_demo_steps.py
  binary_search_demo_visual.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#229 Submission of Lab 03 by BT24S05F001
  binary_search.py
  binary_search_demo_steps.py
  binary_search_demo_visual.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#231 Submission of Lab 03 by BT23F05F064
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#232 Submission of Lab 03 by BT24S05F006
  binary_search.py
  binary_search_demo_steps.py
  binary_search_demo_visual.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#233 Submission of Lab 00 by BT23F05F024
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00

#246 Submission of Lab 03 by BT23F05F025
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#234 Submission of Lab 01 by BT23F05F024
  countdown.py
  print_letters.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#250 Submission of Lab 03 by BT23F05F059
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: 🎉 Accepted, Lab 03

#156 Submission of Lab 03 by BT23F05F051
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: 🎉 Accepted, Lab 03

#257 Submission of Lab 04 by BT23F05F002
  task_4.1.py
  task_4.2.py
  task_4.3.py
  task_4.4.py
  task_4.5.py
  task_4.6.py
Labels: Lab 04

#262 Submission of Lab 01 by BT23F05F019
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#243 Submission of Lab 03 by BT23F05F035
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: ⚠️ Incomplete, Lab 03

#242 Submission of Lab 03 by BT23F05F030
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: ⚠️ Incomplete, Lab 03

#273 Submission of Lab 01 by BT23F05F013
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#274 Submission of Lab 02 by BT23F05F013
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#275 Submission of Lab 03 by BT23F05F013
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#276 Submission of Lab 04 by BT23F05F013
  task_4.1.py
  task_4.2.py
  task_4.3.py
  task_4.4.py
  task_4.5.py
  task_4.6.py
Labels: Lab 04

#277 Submission of Lab 02 by BT23F05F024
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#278 Submission of Lab 03 by BT23F05F024
  binary_search.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#287 Submission of Lab 05 by BT23F05F023
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#289 Submission of Lab 05 by BT23F05F013
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#321 Submission of Lab 04 by BT23F05F029
  task_4.1.py
  task_4.2.py
  task_4.3.py
  task_4.4.py
  task_4.5.py
  task_4.6.py
Labels: Lab 04

#315 Submission of Lab 06 by BT23F05F013
  task_6.1.py
  task_6.2.py
  task_6.3.py
  task_6.4.py
  task_6.5.py
  task_6.6.py
Labels: Lab 06

#301 Submission of Lab 05 by BT23F05F064
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#295 Submission of Lab 05 by BT24SO5F005
  prims algorithm.py
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#294 Submission of Lab 02 by BT23F05F062
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#293 Submission of Lab 01 by BT23F05F062
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: Lab 01

#292 Submission of Lab 03 by BT23F05F029
  binary_search.py
  binary_search_demo_steps.py
  binary_search_demo_visual.py
  task_count_occurrences.py
  task_find_smallest_missing_positive.py
  task_guess_the_peak.py
Labels: Lab 03

#291 Submission of Lab 02 by BT23F05F029
  merge_sort_basic.py
  merge_sort_descending.py
  merge_sort_strings.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#323 Submission of Lab 05 by BT24S05F003
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#324 Submission of Lab 05 by BT23F05F039
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#248 Submission of Lab 02 by BT23F05F012
  merge_sort_basic.py
  merge_sort_descending.py
  merge_sort_strings.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: ⚠️ Incomplete, Lab 02

#313 Submission of Lab 06 by BT23F05F012
  task_6.1.py
  task_6.2.py
  task_6.3.py
  task_6.4.py
  task_6.5.py
  task_6.6.py
Labels: ⚠️ Incomplete, Lab 06

#319 Submission of Lab 04 by BT23F05F012
  task_4.1.py
  task_4.2.py
  task_4.3.py
  task_4.4.py
  task_4.5.py
  task_4.6.py
Labels: ⚠️ Incomplete, Lab 04

#78 Submission of Lab 01 by BT23F05F007
  factorial.py
  task_print_array_backward.py
  task_reverse_digits.py
  task_sum_even_numbers.py
Labels: ⚠️ Incomplete, Lab 01

#332 Submission of Lab 05 by BT23F05F036
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#343 Submission of Lab 00 by BT23F05F012
  a.py
  b.py
  c.py
  d.py
  e.py
  f.py
  g.py
  h.py
  i.py
  j.py
  k.py
  l.py
  m.py
  n.py
  o.py
  p.py
  q.py
  r.py
  s.py
  t.py
  u.py
  v.py
  w.py
  x.py
  y.py
  z+++.py
  z++.py
  z+.py
  z.py
Labels: Lab 00

#346 Submission of Lab 05 by BT23F05F029
  task_5.1.py
  task_5.2.py
  task_5.3.py
  task_5.4.py
  task_5.5.py
  task_5.6.py
Labels: Lab 05

#347 Submission of Lab 02 by BT23F05F012
  merge_sort_basic.py
  merge_sort_descending.py
  merge_sort_strings.py
  task_count_inversions.py
  task_merge_sorted_lists.py
  task_sort_student_scores.py
Labels: Lab 02

#335 Submission of Lab 04 by BT23F05F025
  task_4.1.py
  task_4.2.py
  task_4.3.py
  task_4.4.py
  task_4.5.py
  task_4.6.py
Labels: Lab 04
